spring.application.name=TaxiBooking
server.port=${PORT:8080}
#db config
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DATABASE_URL}

spring.datasource.username=${DATABASE_USERNAME}

spring.datasource.password=${DATABASE_PASSWORD}
#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format-sql=true
#thymleaf config
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
#server error config
server.error.include-message=always
server.error.include-binding-errors=always